### ISSUE TITLE
deleteContainer only deletes first file for that container

### ISSUE THREAD

**Issue by eggerdo** [MrMartiniMo/loopback-component-storage-gridfs#1]
shouldn't the line [gridfs-service.js#74](https://github.com/MrMartiniMo/loopback-component-storage-gridfs/blob/8d69836d85a70e227725bc8608f49f2a6ff55d9e/lib/gridfs-service.js#L74) be changed from
`collection.deleteOne({`
to
`collection.deleteMany({`
so that all entries with given container name are deleted? As it is now, only the first file with this container name is deleted. Otherwise, if this is indeed the intended behaviour, the name `deleteContainer` may be misleading.

Greets,
Dominik

**Comment by MrMartiniMo** [comment]
Hi Dominik,
thanks for your response, you're right.
I will fix that immediately. :)

Greets
Mo
